// ui/src/pages/Login/Login.tsx
import { IconBrandGithub } from '@tabler/icons-react'
import UsersApi from '@weblens/api/UserApi'
import WeblensLogo from '@weblens/components/Logo.tsx'
import { useSessionStore } from '@weblens/components/UserInfo'
import WeblensButton from '@weblens/lib/WeblensButton.tsx'
import WeblensInput from '@weblens/lib/WeblensInput.tsx'
import { ErrorHandler } from '@weblens/types/Types'
import User from '@weblens/types/user/User'
import { AxiosError } from 'axios'
import { useCallback, useEffect, useState } from 'react'

const Login = () => {
    const [userInput, setUserInput] = useState('')
    const [passInput, setPassInput] = useState('')
    const [loading, setLoading] = useState(false)
    const [formError, setFormError] = useState('')

    const setUser = useSessionStore((state) => state.setUser)
    const doLogin = useCallback(async (username: string, password: string) => {
        setLoading(true)
        if (username === '' || password === '') {
            return Promise.reject(
                new Error('username and password must not be empty')
            )
        }
        return UsersApi.loginUser({ username, password })
            .then((res) => {
                const user = new User(res.data)
                user.isLoggedIn = true
                setUser(user)
            })
            .catch((err: AxiosError) => {
                setLoading(false)
                if (err.status === 401) {
                    setFormError('Invalid username or password')
                } else {
                    setFormError('An error occurred')
                }
            })
    }, [])

    useEffect(() => {
        if (formError !== '') {
            setFormError('')
        }
    }, [userInput, passInput])

    return (
        <div className="bg-wl-background m-auto flex h-screen max-h-screen flex-col items-center justify-center gap-2 sm:justify-normal lg:my-0">
            <div className="flex w-full justify-center text-center sm:mt-80">
                <WeblensLogo size={100} />
                <h1 className="mt-auto">EBLENS</h1>
            </div>
            <form
                id="login"
                action="#"
                className="mx-auto mt-8 flex w-96 max-w-full min-w-0 flex-col gap-3 px-4"
                onSubmit={(e) => {
                    e.preventDefault()
                    e.stopPropagation()
                    doLogin(userInput, passInput).catch(ErrorHandler)
                }}
            >
                <WeblensInput
                    placeholder="Username"
                    value={userInput}
                    autoFocus
                    valueCallback={setUserInput}
                    squareSize={44}
                    autoComplete="username"
                />
                <WeblensInput
                    placeholder="Password"
                    value={passInput}
                    valueCallback={setPassInput}
                    squareSize={44}
                    password
                    autoComplete="current-password"
                />
                {formError && (
                    <span className="text-center text-red-500">
                        {formError}
                    </span>
                )}
                <div className="my-3">
                    <WeblensButton
                        label={loading ? 'Signing in...' : 'Sign in'}
                        fillWidth
                        squareSize={50}
                        disabled={
                            userInput === '' || passInput === '' || loading
                        }
                        centerContent
                        type="submit"
                        // setButtonRef={setButtonRef}
                    />
                </div>
                <div className="border-color-border-primary flex items-center justify-center gap-2 border-t-[1px] p-2">
                    <span className="text-color-text-primary ml-auto">
                        New Here?
                    </span>
                    <a href="/signup">Request an Account</a>
                </div>
            </form>
            <a
                href="https://github.com/ethanrous/weblens"
                className="absolute right-0 bottom-0 m-4 flex flex-row bg-transparent"
                target="_blank"
                rel="noreferrer"
            >
                <IconBrandGithub />
                GitHub
            </a>
        </div>
    )
}

export default Login

// weblens-vue/weblens-nuxt/pages/login.vue
<template>
    <div
        v-if="!userStore.user.isLoggedIn.get({ default: false })"
        :class="{ 'page-root items-center p-8': true }"
    >
        <div
            :class="{
                'bg-background-primary border-border-primary relative z-10 m-auto flex h-max max-h-screen min-w-0 flex-col items-center justify-center gap-2 rounded-2xl border p-8 shadow-2xl sm:justify-normal lg:my-0': true,
            }"
        >
            <div class="flex w-full justify-center text-center">
                <Logo :size="100" />
                <h1 class="xs:inline-block mt-auto hidden">EBLENS</h1>
            </div>
            <form
                id="login"
                action="#"
                class="mx-auto mt-8 flex w-96 max-w-full min-w-0 flex-col gap-3 px-4"
                @submit="
                    (e) => {
                        e.preventDefault()
                        e.stopPropagation()
                        doLogin()
                    }
                "
            >
                <WeblensInput
                    v-model:value="username"
                    placeholder="Username"
                    auto-focus
                />
                <WeblensInput
                    v-model:value="password"
                    placeholder="Password"
                    password
                />
                <span
                    v-if="formError"
                    class="text-center text-red-500"
                >
                    {{ formError }}
                </span>
                <div class="my-3">
                    <WeblensButton
                        :label="loading ? 'Signing in...' : 'Sign in'"
                        fill-width
                        :square-size="50"
                        :disabled="username === '' || password.length < 6 || loading"
                        center-content
                    />
                </div>
                <div class="border-color-border-primary flex items-center justify-center gap-2 border-t p-2">
                    <span class="text-color-text-primary ml-auto">New Here?</span>
                    <a href="/signup">Request an Account</a>
                </div>
            </form>
        </div>
        <a
            href="https://github.com/ethanrous/weblens"
            :class="{ 'absolute right-0 bottom-0 m-4 flex flex-row bg-transparent': true }"
            target="_blank"
            rel="noreferrer"
        >
            <IconBrandGithub />
            GitHub
        </a>
    </div>
</template>

<script setup lang="ts">
import { IconBrandGithub } from '@tabler/icons-vue'
import { onKeyDown } from '@vueuse/core'
import type { AxiosError } from 'axios'
import { useWeblensAPI } from '~/api/AllApi'
import Logo from '~/components/atom/Logo.vue'
import WeblensButton from '~/components/atom/WeblensButton.vue'
import WeblensInput from '~/components/atom/WeblensInput.vue'
import useLocationStore from '~/stores/location'
import User from '~/types/user'

const username = ref('')
const password = ref('')
const loading = ref(false)
const formError = ref<string | null>(null)

const userStore = useUserStore()
const locationStore = useLocationStore()

onKeyDown('Enter', doLogin)

async function doLogin() {
    formError.value = ''

    if (username.value === '' || password.value === '') {
        formError.value = 'username and password must not be empty'
        return
    }

    loading.value = true

    return useWeblensAPI()
        .UsersAPI.loginUser({ username: username.value, password: password.value })
        .then((res) => {
            const user = new User(res.data)

            userStore.setUser(user, true)

            return locationStore.homeOrReturnTo()
        })
        .catch((err: AxiosError) => {
            loading.value = false
            if (err.status === 401) {
                formError.value = 'Invalid username or password'
            } else {
                formError.value = err.message || 'An error occurred'
            }
        })
}
</script>
