// ui/src/components/filebrowser/contextMenu/ShareModal.tsx
import {
    IconChevronRight,
    IconLink,
    IconPlus,
    IconUser,
    IconUsers,
    IconUsersPlus,
} from '@tabler/icons-react'
import {
    QueryObserverResult,
    RefetchOptions,
    useQuery,
} from '@tanstack/react-query'
import UsersApi from '@weblens/api/UserApi'
import { PermissionsParams, UserInfo } from '@weblens/api/swag'
import WeblensButton from '@weblens/lib/WeblensButton'
import WeblensInput from '@weblens/lib/WeblensInput'
import { useClick } from '@weblens/lib/hooks'
import { useFileBrowserStore } from '@weblens/store/FBStateControl'
import { ErrorHandler } from '@weblens/types/Types'
import WeblensFile, { FbMenuModeT } from '@weblens/types/files/File'
import { WeblensShare } from '@weblens/types/share/share'
import { Ref, useEffect, useRef, useState } from 'react'

async function toggleParam(
    username: string,
    share: WeblensShare,
    param: keyof PermissionsParams
) {
    const existingPerms = share.permissions[username]
    await share.updateAccessorPerms(username, {
        ...existingPerms,
        [param]: !existingPerms[param],
    })
}

function UserSearch({
    accessors,
    addUser,
}: {
    accessors: UserInfo[]
    addUser: (username: UserInfo) => Promise<void>
}) {
    const [userSearch, setUserSearch] = useState('')
    const [searchMenuOpen, setSearchMenuOpen] = useState(false)
    const [userSearchResults, setUserSearchResults] = useState<UserInfo[]>([])
    const searchRef = useRef<HTMLInputElement>(null)

    useClick(() => {
        setSearchMenuOpen(false)
    }, searchRef.current)

    useEffect(() => {
        if (userSearch.length < 2) {
            setUserSearchResults([])
            return
        }
        UsersApi.searchUsers(userSearch)
            .then((res) => {
                if (!res.data) {
                    setUserSearchResults([])
                    return
                }
                const searchResults = res.data.filter(
                    (u) =>
                        accessors.findIndex(
                            (val) => val.username === u.username
                        ) === -1
                )

                setUserSearchResults(searchResults)
            })
            .catch((err) => {
                console.error('Failed to search users', err)
            })
    }, [userSearch, accessors])

    return (
        <div
            ref={searchRef}
            className="relative flex w-full flex-col items-center gap-1"
        >
            <div className="z-20 mt-3 mb-3 h-10 w-full">
                <WeblensInput
                    value={userSearch}
                    valueCallback={setUserSearch}
                    placeholder="Add users"
                    onComplete={null}
                    Icon={IconUsersPlus}
                    openInput={() => setSearchMenuOpen(true)}
                />
            </div>
            {userSearchResults.length !== 0 && searchMenuOpen && (
                <div className="no-scrollbar bg-card-background-primary floating-card absolute z-10 mt-14 flex max-h-32 w-full flex-col gap-1 rounded-sm border">
                    {userSearchResults.map((user) => {
                        return (
                            <div
                                className="hover:bg-card-background-hover relative flex h-10 w-full cursor-pointer flex-row items-center rounded p-4"
                                key={user.username}
                                onClick={async (e) => {
                                    e.stopPropagation()
                                    e.preventDefault()
                                    await addUser(user)
                                    setUserSearchResults((p) => {
                                        const newP = [...p]
                                        newP.splice(newP.indexOf(user), 1)
                                        return newP
                                    })
                                }}
                            >
                                <span>{user.fullName}</span>
                                <span className="text-text-secondary ml-1">
                                    [{user.username}]
                                </span>
                                <IconPlus className="ml-auto" />
                            </div>
                        )
                    })}
                </div>
            )}
        </div>
    )
}

function UserPermissions({
    user,
    share,
    refetch,
}: {
    user: UserInfo
    share: WeblensShare
    refetch: (
        options?: RefetchOptions
    ) => Promise<QueryObserverResult<WeblensShare, Error>>
}) {
    return (
        <div className="border-l-border-primary ml-2 flex w-1/2 flex-col items-center border-l-2 px-2">
            <h5>{user.username} Permissions</h5>
            <div className="flex flex-col gap-1 px-10">
                <WeblensButton
                    label="Can Download"
                    fillWidth
                    flavor={
                        share.permissions[user.username].canDownload
                            ? 'default'
                            : 'outline'
                    }
                    onClick={async () => {
                        await toggleParam(user.username, share, 'canDownload')
                        refetch()
                    }}
                />
                <WeblensButton
                    label="Can Edit"
                    fillWidth
                    flavor={
                        share.permissions[user.username].canEdit
                            ? 'default'
                            : 'outline'
                    }
                    onClick={async () => {
                        await toggleParam(user.username, share, 'canEdit')
                        refetch()
                    }}
                />
                <WeblensButton
                    label="Can Delete"
                    fillWidth
                    flavor={
                        share.permissions[user.username].canDelete
                            ? 'default'
                            : 'outline'
                    }
                    onClick={async () => {
                        await toggleParam(user.username, share, 'canDelete')
                        refetch()
                    }}
                />

                <WeblensButton
                    label="Unshare"
                    danger
                    className="mt-4"
                    fillWidth
                    onClick={async () => {
                        await share.removeAccessor(user.username)
                        refetch()
                    }}
                />
            </div>
        </div>
    )
}

export function ShareModal({
    targetFile,
    ref,
}: {
    targetFile: WeblensFile
    ref: Ref<HTMLDivElement>
}) {
    const menuMode = useFileBrowserStore((state) => state.menuMode)
    const setMenu = useFileBrowserStore((state) => state.setMenu)
    const folderInfo = useFileBrowserStore((state) => state.folderInfo)

    const [focusedUser, setFocusedUser] = useState<UserInfo>(null)

    if (!targetFile) {
        targetFile = folderInfo
    }

    const {
        data: share,
        refetch,
        isLoading,
    } = useQuery<WeblensShare>({
        queryKey: ['share', targetFile.Id()],
        initialData: null,
        queryFn: async () => {
            const share = await targetFile.GetShare(true).catch(ErrorHandler)

            console.log('GOT SHREA', share)
            if (!share) {
                return null
            }

            return share
        },
    })

    useEffect(() => {
        if (!share) {
            return
        }

        if (share.accessors.length === 0) {
            setFocusedUser(null)
        }
    }, [share])

    if (menuMode === FbMenuModeT.Closed) {
        return <></>
    }

    return (
        <div
            className="fullscreen-modal"
            onClick={(e) => e.stopPropagation()}
            ref={ref}
        >
            {isLoading && (
                <div className="bg-background-primary absolute top-0 left-0 h-full w-full opacity-50" />
            )}

            <div className="bg-background-primary floating-card m-auto flex h-1/2 w-1/2 flex-col rounded-lg p-5">
                <h3 className="mb-3 flex min-h-max w-full max-w-full truncate text-nowrap">
                    {'Share "' + targetFile.GetFilename() + '"'}
                </h3>
                <div className="flex w-full flex-row gap-1">
                    <WeblensButton
                        label={share?.public ? 'Public' : 'Private'}
                        Left={share?.public ? IconUsers : IconUser}
                        flavor={share?.public ? 'default' : 'outline'}
                        fillWidth
                        onClick={async (e) => {
                            e.stopPropagation()
                            await share.setPublic(!share.public)
                            refetch()
                        }}
                    />
                    <WeblensButton
                        label={'Copy Link'}
                        Left={IconLink}
                        fillWidth
                        disabled={!share?.shareId}
                        tooltip={!share?.shareId ? 'Not shared' : ''}
                    />
                </div>

                <UserSearch
                    accessors={share?.accessors}
                    addUser={async (user: UserInfo) => {
                        await share.addAccessor(user.username)
                        refetch()
                    }}
                />

                <h4 className="mb-2 w-max">Shared With</h4>

                <div className="no-scrollbar flex h-full w-full rounded-sm border p-2">
                    {share && share.accessors.length === 0 && (
                        <span className="m-auto">Not Shared</span>
                    )}
                    {share &&
                        share.accessors.length !== 0 &&
                        share.accessors.map((u: UserInfo) => {
                            return (
                                <div
                                    key={u.username}
                                    className="bg-background-secondary hover:bg-card-background-hover group/user flex h-10 w-full cursor-pointer items-center rounded p-2 transition"
                                    onClick={() => {
                                        if (focusedUser === u) {
                                            setFocusedUser(null)
                                        } else {
                                            setFocusedUser(u)
                                        }
                                    }}
                                >
                                    <span>{u.fullName}</span>
                                    <span className="text-color-text-secondary ml-1">
                                        [{u.username}]
                                    </span>
                                    <IconChevronRight className="text-text-tertiary ml-auto" />
                                </div>
                            )
                        })}
                    {focusedUser && (
                        <UserPermissions
                            user={focusedUser}
                            share={share}
                            refetch={refetch}
                        />
                    )}
                </div>
                <div className="mt-3 ml-auto flex w-1/3">
                    <WeblensButton
                        fillWidth
                        label="Done"
                        onClick={() =>
                            setMenu({ menuState: FbMenuModeT.Closed })
                        }
                    />
                </div>
            </div>
        </div>
    )
}

// weblens-vue/weblens-nuxt/components/organism/ShareModal.vue
<template>
    <div
        :class="{
            'fullscreen-modal p-12 transition xl:p-48': true,
            'pointer-events-none opacity-0': !menuStore.isSharing,
        }"
    >
        <div
            ref="modal"
            :class="{
                'bg-background-primary flex h-full w-full flex-col gap-4 overflow-y-auto rounded border p-4': true,
            }"
            @click.stop
        >
            <div :class="{ 'flex items-center gap-1': true }">
                <h4>Share</h4>
                <FileIcon
                    :file="file"
                    :with-name="true"
                />
            </div>

            <div :class="{ 'z-99 flex w-full items-center gap-2': true }">
                <UserSearch
                    :class="{ 'min-w-10': true }"
                    :exclude-fn="excludeFn"
                    @select:user="addAccessor"
                />
            </div>
            <Table
                :columns="['username', 'canDownload', 'canEdit', 'canDelete', 'unshare']"
                :rows="rows"
            />
            <span :class="{ 'text-text-secondary mt-4': true }">Public Share Settings</span>
            <Table
                :columns="['public', 'canViewFiles', 'canDownload', 'canEdit']"
                :rows="publicShareRows"
            />

            <div :class="{ 'mt-auto inline-flex w-full items-center gap-2': true }">
                <WeblensButton @click="doTimeline = !doTimeline">
                    <IconPhoto v-if="doTimeline" />
                    <IconFolder v-if="!doTimeline" />
                </WeblensButton>

                <CopyBox
                    :text="share?.ID() ? share?.GetLink(doTimeline) : undefined"
                    :class="{ grow: true }"
                />
            </div>

            <div :class="{ 'flex gap-2': true }">
                <WeblensButton
                    label="Revoke Share"
                    :flavor="'danger'"
                    :disabled="!share?.ID()"
                    @click.stop="deleteShare()"
                >
                    <IconUserOff />
                </WeblensButton>
                <WeblensButton
                    label="Done"
                    :class="{ 'ml-auto w-1/4': true }"
                    @click.stop="menuStore.setSharing(false)"
                />
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { IconFolder, IconLock, IconLockOpen, IconPhoto, IconUserOff } from '@tabler/icons-vue'
import WeblensButton from '../atom/WeblensButton.vue'
import type WeblensFile from '~/types/weblensFile'
import FileIcon from '../atom/FileIcon.vue'
import UserSearch from '../molecule/UserSearch.vue'
import CopyBox from '../molecule/CopyBox.vue'
import { onClickOutside } from '@vueuse/core'
import Table from '../atom/Table.vue'
import type { UserInfo } from '@ethanrous/weblens-api'
import { TableType, type TableColumn, type TableColumns, type TableRow } from '~/types/table'
import { useWeblensAPI } from '~/api/AllApi'
import { UNAUTHENTICATED_USER_NAME } from '~/types/user'

const menuStore = useContextMenuStore()

const doTimeline = ref<boolean>(false)

const modal = ref<HTMLDivElement>()
onClickOutside(modal, () => {
    if (menuStore.isSharing) menuStore.setSharing(false)
})

const props = defineProps<{
    file: WeblensFile
}>()

const { data: share } = useAsyncData(
    'share-' + props.file.ID(),
    async () => {
        return await props.file.GetShare()
    },
    { deep: false, watch: [() => props.file.ID()] },
)

const accessors = computed<TableColumns>(() => {
    if (!share.value) {
        return []
    }

    return share.value.accessors.map<Record<string, TableColumn>>((u) => ({
        username: {
            tableType: TableType.Text,
            text: u.username,
        },
        canDownload: {
            tableType: TableType.Checkbox,
            checked: share.value?.permissions[u.username]?.canDownload ?? false,
            onchanged: async (c: boolean) => {
                if (!share.value) return
                await share.value.updateAccessorPerms(u.username, {
                    ...share.value?.permissions[u.username],
                    canDownload: c,
                })
                share.value = share.value.clone()
            },
        },
        canEdit: {
            tableType: TableType.Checkbox,
            checked: share.value?.permissions[u.username]?.canEdit ?? false,
            onchanged: async (c: boolean) => {
                if (!share.value) return
                await share.value.updateAccessorPerms(u.username, {
                    ...share.value?.permissions[u.username],
                    canEdit: c,
                })
                share.value = share.value.clone()
            },
        },
        canDelete: {
            tableType: TableType.Checkbox,
            checked: share.value?.permissions[u.username]?.canDelete ?? false,
            onchanged: async (c: boolean) => {
                if (!share.value) return
                await share.value.updateAccessorPerms(u.username, {
                    ...share.value?.permissions[u.username],
                    canDelete: c,
                })

                share.value = share.value.clone()
            },
        },
        unshare: {
            flavor: 'danger',
            tableType: TableType.Button,
            icon: IconUserOff,
            onClick: async () => {
                if (!share.value) return
                await share.value.removeAccessor(u.username)
                share.value = share.value.clone()
            },
        },
    }))
})

const rows = computed<TableRow[]>(() => {
    let rows: TableRow[] = [...accessors.value]
    if (rows.length === 0) {
        rows = [
            {
                sectionHeader: true,
                text: 'Not shared with anyone',
                icon: IconUserOff,
                className: 'text-text-tertiary',
            },
        ]
    }

    return rows
})

const publicShareRows = computed<TableRow[]>(() => {
    if (!share.value) {
        return []
    }

    return [
        {
            public: {
                tableType: TableType.Button,
                checked: share.value.IsPublic(),
                label: share.value.IsPublic() ? 'Public' : 'Private',
                type: share.value.IsPublic() ? 'default' : 'outline',
                icon: share.value.IsPublic() ? IconLockOpen : IconLock,
                onClick: async () => {
                    await toggleIsPublic()
                },
            },
            canViewFiles: {
                tableType: TableType.Checkbox,
                checked: share.value?.permissions?.[UNAUTHENTICATED_USER_NAME]?.canView ?? false,
                disabled: !share.value.IsPublic(),
                onchanged: async (c: boolean) => {
                    if (!share.value) return
                    await share.value.updateAccessorPerms(UNAUTHENTICATED_USER_NAME, {
                        ...share.value?.permissions?.[UNAUTHENTICATED_USER_NAME],
                        canView: c,
                    })

                    share.value = share.value.clone()
                },
            },
            canDownload: {
                tableType: TableType.Checkbox,
                checked: share.value?.permissions?.[UNAUTHENTICATED_USER_NAME]?.canDownload ?? false,
                disabled: !share.value.IsPublic(),
                onchanged: async (c: boolean) => {
                    if (!share.value) return
                    await share.value.updateAccessorPerms(UNAUTHENTICATED_USER_NAME, {
                        ...share.value?.permissions?.[UNAUTHENTICATED_USER_NAME],
                        canDownload: c,
                    })

                    share.value = share.value.clone()
                },
            },
            canEdit: {
                tableType: TableType.Checkbox,
                checked: share.value?.permissions?.[UNAUTHENTICATED_USER_NAME]?.canEdit ?? false,
                disabled: !share.value.IsPublic(),
                onchanged: async (c: boolean) => {
                    if (!share.value) return
                    await share.value.updateAccessorPerms(UNAUTHENTICATED_USER_NAME, {
                        ...share.value?.permissions?.[UNAUTHENTICATED_USER_NAME],
                        canEdit: c,
                    })

                    share.value = share.value.clone()
                },
            },
            // canDelete: {
            //     tableType: TableType.Checkbox,
            //     checked: share.value?.permissions?.[UNAUTHENTICATED_USER_NAME]?.canDelete ?? false,
            //     disabled: !share.value.IsPublic(),
            //     onchanged: async (c: boolean) => {
            //         if (!share.value) return
            //         await share.value.updateAccessorPerms(UNAUTHENTICATED_USER_NAME, {
            //             ...share.value?.permissions?.[UNAUTHENTICATED_USER_NAME],
            //             canDelete: c,
            //         })
            //
            //         share.value = share.value.clone()
            //     },
            // },
        },
    ]
})

async function addAccessor(user: UserInfo) {
    if (!share.value) {
        console.error('No share to add accessor')
        return
    }

    await share.value.addAccessor(user.username)
    share.value = share.value.clone()
}

function excludeFn(u: UserInfo) {
    if (share.value?.accessors.map((u) => u.username).includes(u.username)) {
        return false
    }

    return true
}

async function toggleIsPublic() {
    if (!share.value) {
        console.error('No share to toggle isPublic')
        return
    }

    await share.value.toggleIsPublic()
}

async function deleteShare() {
    if (!share.value) {
        console.error('No share to delete')
        return
    }

    try {
        await useWeblensAPI().SharesAPI.deleteFileShare(share.value.ID())
        share.value = null
        menuStore.setSharing(false)
    } catch (e) {
        console.error('Failed to delete share', e)
    }
}
</script>
